name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install Tailwind CSS and Flowbite
        run: |
          npm install -D tailwindcss postcss autoprefixer
          npx tailwindcss init -p
          npm install flowbite

      - name: Build your site
        run: |
          # Assuming your build command is something like npm run build or yarn build
          npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs # Change this to the directory where your built files are located

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Specify the directory containing the files to deploy
          dir: github-pages # Change this to the directory where your built files are located
